# Generated by Django 4.2.1 on 2023-06-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_protein', '0003_phage_protein_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_protein_MGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phage_Acession_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Source', models.CharField(blank=True, max_length=30, null=True)),
                ('Start_location', models.IntegerField(blank=True, null=True)),
                ('Stop_location', models.IntegerField(blank=True, null=True)),
                ('Strand', models.CharField(blank=True, max_length=10, null=True)),
                ('Protein_id', models.CharField(blank=True, max_length=220, null=True)),
                ('Protein_product', models.TextField(blank=True, null=True)),
                ('Protein_function_classification', models.TextField(blank=True, null=True)),
                ('molecular_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('aromaticity', models.CharField(blank=True, max_length=100, null=True)),
                ('instability_index', models.CharField(blank=True, max_length=100, null=True)),
                ('isoelectric_point', models.CharField(blank=True, max_length=100, null=True)),
                ('Helix_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Turn_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Sheet_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Reduced_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('Oxidized_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'phage_protein_MGV',
                'verbose_name_plural': 'phage_protein_MGV',
                'db_table': 'phage_protein_MGV',
            },
        ),
        migrations.CreateModel(
            name='phage_protein_NCBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phage_Acession_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Source', models.CharField(blank=True, max_length=30, null=True)),
                ('Start_location', models.IntegerField(blank=True, null=True)),
                ('Stop_location', models.IntegerField(blank=True, null=True)),
                ('Strand', models.CharField(blank=True, max_length=10, null=True)),
                ('Protein_id', models.CharField(blank=True, max_length=220, null=True)),
                ('Protein_product', models.TextField(blank=True, null=True)),
                ('Protein_function_classification', models.TextField(blank=True, null=True)),
                ('molecular_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('aromaticity', models.CharField(blank=True, max_length=100, null=True)),
                ('instability_index', models.CharField(blank=True, max_length=100, null=True)),
                ('isoelectric_point', models.CharField(blank=True, max_length=100, null=True)),
                ('Helix_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Turn_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Sheet_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Reduced_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('Oxidized_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'phage_protein_NCBI',
                'verbose_name_plural': 'phage_protein_NCBI',
                'db_table': 'phage_protein_NCBI',
            },
        ),
        migrations.CreateModel(
            name='phage_protein_PhagesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phage_Acession_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Source', models.CharField(blank=True, max_length=30, null=True)),
                ('Start_location', models.IntegerField(blank=True, null=True)),
                ('Stop_location', models.IntegerField(blank=True, null=True)),
                ('Strand', models.CharField(blank=True, max_length=10, null=True)),
                ('Protein_id', models.CharField(blank=True, max_length=220, null=True)),
                ('Protein_product', models.TextField(blank=True, null=True)),
                ('Protein_function_classification', models.TextField(blank=True, null=True)),
                ('molecular_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('aromaticity', models.CharField(blank=True, max_length=100, null=True)),
                ('instability_index', models.CharField(blank=True, max_length=100, null=True)),
                ('isoelectric_point', models.CharField(blank=True, max_length=100, null=True)),
                ('Helix_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Turn_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Sheet_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Reduced_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('Oxidized_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'phage_protein_PhagesDB',
                'verbose_name_plural': 'phage_protein_PhagesDB',
                'db_table': 'phage_protein_PhagesDB',
            },
        ),
        migrations.CreateModel(
            name='phage_protein_TemPhD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phage_Acession_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Source', models.CharField(blank=True, max_length=30, null=True)),
                ('Start_location', models.IntegerField(blank=True, null=True)),
                ('Stop_location', models.IntegerField(blank=True, null=True)),
                ('Strand', models.CharField(blank=True, max_length=10, null=True)),
                ('Protein_id', models.CharField(blank=True, max_length=220, null=True)),
                ('Protein_product', models.TextField(blank=True, null=True)),
                ('Protein_function_classification', models.TextField(blank=True, null=True)),
                ('molecular_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('aromaticity', models.CharField(blank=True, max_length=100, null=True)),
                ('instability_index', models.CharField(blank=True, max_length=100, null=True)),
                ('isoelectric_point', models.CharField(blank=True, max_length=100, null=True)),
                ('Helix_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Turn_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Sheet_secondary_structure_fraction', models.CharField(blank=True, max_length=100, null=True)),
                ('Reduced_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('Oxidized_molar_extinction_coefficient', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'phage_protein_TemPhD',
                'verbose_name_plural': 'phage_protein_TemPhD',
                'db_table': 'phage_protein_TemPhD',
            },
        ),
        migrations.RenameModel(
            old_name='phage_protein_2',
            new_name='phage_protein_GPD',
        ),
        migrations.RenameModel(
            old_name='phage_protein_1',
            new_name='phage_protein_GVD',
        ),
        migrations.AlterModelOptions(
            name='phage_protein_gpd',
            options={'verbose_name': 'phage_protein_GPD', 'verbose_name_plural': 'phage_protein_GPD'},
        ),
        migrations.AlterModelOptions(
            name='phage_protein_gvd',
            options={'verbose_name': 'phage_protein_GVD', 'verbose_name_plural': 'phage_protein_GVD'},
        ),
        migrations.AlterModelTable(
            name='phage_protein_gpd',
            table='phage_protein_GPD',
        ),
        migrations.AlterModelTable(
            name='phage_protein_gvd',
            table='phage_protein_GVD',
        ),
    ]
