# Generated by Django 4.1.2 on 2023-06-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_protein', '0004_phage_protein_mgv_phage_protein_ncbi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_protein_anticrispr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protein_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Source', models.CharField(blank=True, max_length=200, null=True)),
                ('Phage_Acession_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('dataset', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'phage_protein_anticrispr',
                'verbose_name_plural': 'phage_protein_anticrispr',
                'db_table': 'phage_protein_anticrispr',
            },
        ),
    ]
