# Generated by Django 4.2.1 on 2023-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_protein', '0006_phage_protein_tmhmm_gpd_phage_protein_tmhmm_gvd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_crispr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strain', models.CharField(blank=True, max_length=200, null=True)),
                ('Phage_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Sequence_basename', models.CharField(blank=True, max_length=200, null=True)),
                ('Duplicated_Spacers', models.CharField(blank=True, max_length=200, null=True)),
                ('CRISPR_Id', models.CharField(blank=True, max_length=200, null=True)),
                ('CRISPR_Start', models.CharField(blank=True, max_length=200, null=True)),
                ('CRISPR_End', models.CharField(blank=True, max_length=200, null=True)),
                ('CRISPR_Length', models.CharField(blank=True, max_length=200, null=True)),
                ('Potential_Orientation_AT', models.CharField(blank=True, max_length=200, null=True)),
                ('CRISPRDirection', models.CharField(blank=True, max_length=200, null=True)),
                ('Consensus_Repeat', models.CharField(blank=True, max_length=200, null=True)),
                ('Repeat_ID_CRISPRdb', models.CharField(blank=True, max_length=200, null=True)),
                ('Nb_CRISPRs_with_same_Repeat_CRISPRdb', models.CharField(blank=True, max_length=200, null=True)),
                ('Repeat_Length', models.CharField(blank=True, max_length=200, null=True)),
                ('Spacers_Nb', models.CharField(blank=True, max_length=200, null=True)),
                ('Mean_size_Spacers', models.CharField(blank=True, max_length=200, null=True)),
                ('Standard_Deviation_Spacers', models.CharField(blank=True, max_length=200, null=True)),
                ('Nb_Repeats_matching_Consensus', models.CharField(blank=True, max_length=200, null=True)),
                ('Ratio_Repeats_match_TotalRepeat', models.CharField(blank=True, max_length=200, null=True)),
                ('Conservation_Repeats_identity', models.CharField(blank=True, max_length=200, null=True)),
                ('EBcons_Repeats', models.CharField(blank=True, max_length=200, null=True)),
                ('Conservation_Spacers_identity', models.CharField(blank=True, max_length=200, null=True)),
                ('EBcons_Spacers', models.CharField(blank=True, max_length=200, null=True)),
                ('Repeat_Length_plus_mean_size_Spacers', models.CharField(blank=True, max_length=200, null=True)),
                ('Ratio_Repeat_mean_Spacers_Length', models.CharField(blank=True, max_length=200, null=True)),
                ('CRISPR_found_in_DB_if_sequence_IDs_are_similar', models.CharField(blank=True, max_length=200, null=True)),
                ('Evidence_Level', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'phage_crispr',
                'verbose_name_plural': 'phage_crispr',
                'db_table': 'phage_crispr',
            },
        ),
    ]
