# Generated by Django 4.2.1 on 2023-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_protein', '0007_phage_crispr'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_terminators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phage_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Terminator_Id', models.CharField(blank=True, max_length=200, null=True)),
                ('Start', models.CharField(blank=True, max_length=200, null=True)),
                ('Stop', models.CharField(blank=True, max_length=200, null=True)),
                ('Sense', models.CharField(blank=True, max_length=200, null=True)),
                ('Loc', models.CharField(blank=True, max_length=200, null=True)),
                ('Confidence', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'phage_terminators',
                'verbose_name_plural': 'phage_terminators',
                'db_table': 'phage_terminators',
            },
        ),
    ]
