# Generated by Django 4.2.1 on 2023-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_protein', '0008_phage_terminators'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage_protein_ncbi',
            name='prosequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
