# Generated by Django 4.2.1 on 2023-10-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phage_protein', '0013_phage_protein_chvd_phage_protein_gov2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phage_protein_tmhmm_gpd',
            options={'verbose_name': 'phage_protein_tmhmm_GPD', 'verbose_name_plural': 'phage_protein_tmhmm_GPD'},
        ),
        migrations.AlterModelOptions(
            name='phage_protein_tmhmm_gvd',
            options={'verbose_name': 'phage_protein_tmhmm_GVD', 'verbose_name_plural': 'phage_protein_tmhmm_GVD'},
        ),
        migrations.AlterModelOptions(
            name='phage_protein_tmhmm_mgv',
            options={'verbose_name': 'phage_protein_tmhmm_MGV', 'verbose_name_plural': 'phage_protein_tmhmm_MGV'},
        ),
        migrations.AlterModelOptions(
            name='phage_protein_tmhmm_ncbi',
            options={'verbose_name': 'phage_protein_tmhmm_NCBI', 'verbose_name_plural': 'phage_protein_tmhmm_NCBI'},
        ),
        migrations.AlterModelOptions(
            name='phage_protein_tmhmm_phagesdb',
            options={'verbose_name': 'phage_protein_tmhmm_PhagesDB', 'verbose_name_plural': 'phage_protein_tmhmm_PhagesDB'},
        ),
        migrations.AlterModelOptions(
            name='phage_protein_tmhmm_temphd',
            options={'verbose_name': 'phage_protein_tmhmm_TemPhD', 'verbose_name_plural': 'phage_protein_tmhmm_TemPhD'},
        ),
        migrations.AlterModelTable(
            name='phage_protein_tmhmm_gpd',
            table='phage_protein_tmhmm_GPD',
        ),
        migrations.AlterModelTable(
            name='phage_protein_tmhmm_gvd',
            table='phage_protein_tmhmm_GVD',
        ),
        migrations.AlterModelTable(
            name='phage_protein_tmhmm_mgv',
            table='phage_protein_tmhmm_MGV',
        ),
        migrations.AlterModelTable(
            name='phage_protein_tmhmm_ncbi',
            table='phage_protein_tmhmm_NCBI',
        ),
        migrations.AlterModelTable(
            name='phage_protein_tmhmm_phagesdb',
            table='phage_protein_tmhmm_PhagesDB',
        ),
        migrations.AlterModelTable(
            name='phage_protein_tmhmm_temphd',
            table='phage_protein_tmhmm_TemPhD',
        ),
    ]
