# Generated by Django 4.2.1 on 2025-03-06 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('gene_name', models.CharField(blank=True, max_length=200, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=200, null=True)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('strand', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'gene',
                'verbose_name_plural': 'gene',
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='isoform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('isoform_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('gene_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=200, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=200, null=True)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('junction_position', models.TextField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=200, null=True)),
                ('isoform_type', models.CharField(blank=True, max_length=200, null=True)),
                ('exon_count', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'isoform',
                'verbose_name_plural': 'isoform',
                'db_table': 'isoform',
            },
        ),
    ]
