# Generated by Django 4.2.1 on 2024-10-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antigen_name', models.CharField(blank=True, max_length=200, null=True)),
                ('antigen_aequence', models.CharField(blank=True, max_length=20, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('antigen_type', models.CharField(blank=True, max_length=20, null=True)),
                ('model_structure', models.CharField(blank=True, max_length=20, null=True)),
                ('href2', models.TextField(blank=True, max_length=500, null=True)),
                ('surface_access', models.CharField(blank=True, max_length=20, null=True)),
                ('href3', models.TextField(blank=True, max_length=500, null=True)),
                ('protein_class', models.CharField(blank=True, max_length=100, null=True)),
                ('database_reference1', models.CharField(blank=True, max_length=20, null=True)),
                ('href4', models.TextField(blank=True, max_length=500, null=True)),
                ('database_reference2', models.CharField(blank=True, max_length=20, null=True)),
                ('href5', models.TextField(blank=True, max_length=500, null=True)),
                ('database_reference3', models.CharField(blank=True, max_length=20, null=True)),
                ('href6', models.TextField(blank=True, max_length=500, null=True)),
                ('source_organism', models.CharField(blank=True, max_length=200, null=True)),
                ('href7', models.TextField(blank=True, max_length=500, null=True)),
                ('literature_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('href8', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'antigen',
                'verbose_name_plural': 'antigen',
                'db_table': 'antigen',
            },
        ),
    ]
