# Generated by Django 4.2.1 on 2025-02-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utrdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_type', models.CharField(blank=True, max_length=200, null=True)),
                ('transcript_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_id', models.CharField(blank=True, max_length=200, null=True)),
                ('chr_start_end_strand', models.CharField(blank=True, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'utrdb',
                'verbose_name_plural': 'utrdb',
                'db_table': 'utrdb',
            },
        ),
    ]
