# Generated by Django 4.1.2 on 2023-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phage_clusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'phage_clusters',
                'verbose_name_plural': 'phage_clusters',
                'db_table': 'phage_clusters',
            },
        ),
    ]
