# Generated by Django 4.2.1 on 2023-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_clusters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phage_clusters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='phage_clusters',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phage_clusters',
            name='tag',
        ),
        migrations.AddField(
            model_name='phage_clusters',
            name='average_gc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage_clusters',
            name='average_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage_clusters',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage_clusters',
            name='member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phage_clusters',
            name='repequence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
