# Generated by Django 4.2.1 on 2023-06-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_clusters', '0002_remove_phage_clusters_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phage_clusters',
            name='repequence',
        ),
        migrations.AddField(
            model_name='phage_clusters',
            name='subclusters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
