# Generated by Django 4.2.1 on 2023-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_clusters', '0003_remove_phage_clusters_repequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage_clusters',
            name='subclusters',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
