# Generated by Django 4.2.1 on 2023-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_clusters', '0004_alter_phage_clusters_subclusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage_clusters',
            name='subclusters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
