# Generated by Django 4.2.1 on 2025-01-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mirtarbase_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirtarbase_id', models.CharField(max_length=200)),
                ('mirna', models.CharField(blank=True, max_length=200, null=True)),
                ('species_mirna', models.CharField(blank=True, max_length=200, null=True)),
                ('target_gene', models.CharField(blank=True, max_length=200, null=True)),
                ('target_gene_entrez_gene_id', models.CharField(blank=True, max_length=200, null=True)),
                ('species_target_gene', models.CharField(blank=True, max_length=200, null=True)),
                ('target_site', models.TextField(blank=True, null=True)),
                ('experiments', models.TextField(blank=True, null=True)),
                ('support_type', models.CharField(blank=True, max_length=200, null=True)),
                ('references_pmid', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'mirtarbase_db',
                'verbose_name_plural': 'mirtarbase_db',
                'db_table': 'mirtarbase_db',
            },
        ),
    ]
