# Generated by Django 4.2.1 on 2023-05-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phage_clusters', '0002_remove_phage_clusters_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_subcluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcluster', models.CharField(blank=True, max_length=200, null=True)),
                ('repequence', models.CharField(blank=True, max_length=200, null=True)),
                ('member', models.IntegerField(blank=True, null=True)),
                ('average_length', models.CharField(blank=True, max_length=200, null=True)),
                ('average_gc', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phage_clusters.phage_clusters')),
            ],
            options={
                'verbose_name': 'phage_subcluster',
                'verbose_name_plural': 'phage_subcluster',
                'db_table': 'phage_subcluster',
            },
        ),
    ]
