# Generated by Django 4.2.1 on 2023-06-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_subcluster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phage_subcluster',
            old_name='repequence',
            new_name='repsequence',
        ),
        migrations.AddField(
            model_name='phage_subcluster',
            name='average_genes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage_subcluster',
            name='average_trna',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage_subcluster',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
