# Generated by Django 4.2.1 on 2023-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_subcluster', '0002_rename_repequence_phage_subcluster_repsequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage_subcluster',
            name='host',
            field=models.TextField(blank=True, null=True),
        ),
    ]
