# Generated by Django 4.2.1 on 2024-10-14 08:17

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mrna_task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=300)),
                ('user_id', models.CharField(max_length=300)),
                ('user_input_path', django.contrib.postgres.fields.hstore.HStoreField()),
                ('is_demo_input', models.BooleanField()),
                ('output_result_path', models.CharField(max_length=500)),
                ('output_log_path', models.CharField(max_length=500)),
                ('analysis_type', models.CharField(max_length=60)),
                ('parameters', django.contrib.postgres.fields.hstore.HStoreField()),
                ('status', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mrna_task',
                'verbose_name_plural': 'mrna_task',
                'db_table': 'mrna_task',
            },
        ),
    ]
