# Generated by Django 4.2.23 on 2025-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tcrabpairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.CharField(blank=True, max_length=300, null=True)),
                ('Alpha', models.CharField(blank=True, max_length=400, null=True)),
                ('Beta', models.CharField(blank=True, max_length=400, null=True)),
                ('umisA', models.FloatField(blank=True, null=True)),
                ('umisB', models.FloatField(blank=True, null=True)),
                ('clonotype_freq', models.IntegerField(blank=True, null=True)),
                ('TRAV', models.CharField(blank=True, max_length=200, null=True)),
                ('TRAJ', models.CharField(blank=True, max_length=200, null=True)),
                ('cdr3A', models.CharField(blank=True, max_length=300, null=True)),
                ('cdr3_ntA', models.CharField(blank=True, max_length=400, null=True)),
                ('readsA', models.IntegerField(blank=True, null=True)),
                ('TRBV', models.CharField(blank=True, max_length=200, null=True)),
                ('TRBJ', models.CharField(blank=True, max_length=200, null=True)),
                ('cdr3B', models.CharField(blank=True, max_length=300, null=True)),
                ('cdr3_ntB', models.CharField(blank=True, max_length=400, null=True)),
                ('readsB', models.IntegerField(blank=True, null=True)),
                ('raw_clonotype_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'tcrabpairing',
                'verbose_name_plural': 'tcrabpairing',
                'db_table': 'tcrabpairing',
            },
        ),
    ]
