# Generated by Django 4.2.1 on 2025-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tissue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tissue_type_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField()),
                ('min_age', models.IntegerField(null=True)),
                ('max_age', models.IntegerField(null=True)),
                ('death_circumstances', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_id', models.IntegerField()),
                ('dataset_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'samples',
                'verbose_name_plural': 'samples',
                'db_table': 'samples',
            },
        ),
    ]
