# Generated by Django 4.1.2 on 2023-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('mid', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('analysis_category', models.CharField(blank=True, max_length=30, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=30, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('task_demo_id', models.IntegerField(blank=True, null=True)),
                ('demo_result_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analysis',
                'db_table': 'analysis',
            },
        ),
    ]
