# Generated by Django 4.1.2 on 2023-06-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phage', '0009_rename_group_phage_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('phage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phage.phage')),
            ],
            options={
                'verbose_name': 'phage_lifestyle',
                'verbose_name_plural': 'phage_lifestyle',
                'db_table': 'phage_lifestyle',
            },
        ),
    ]
