# Generated by Django 4.2.1 on 2023-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_lifestyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage_lifestyle',
            name='accesion_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
