# Generated by Django 4.2.1 on 2023-06-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_lifestyle', '0002_phage_lifestyle_accesion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage_lifestyle',
            name='accesion_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
