# Generated by Django 4.1.2 on 2023-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('output_id', models.IntegerField(blank=True, null=True)),
                ('analysis_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tasks',
                'verbose_name_plural': 'tasks',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='tasks_outputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_paths', models.CharField(blank=True, max_length=30, null=True)),
                ('task_log', models.TextField(blank=True, null=True)),
                ('task_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tasks_outputs',
                'verbose_name_plural': 'tasks_outputs',
                'db_table': 'tasks_outputs',
            },
        ),
    ]
