# Generated by Django 4.2.1 on 2023-06-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_delete_tasks_outputs_remove_tasks_analysis_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='modulelist',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
