# Generated by Django 4.2.1 on 2024-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lineardesign_taskresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrna_task_analysis_type', models.CharField(max_length=60)),
                ('task_id', models.IntegerField()),
                ('seq_name', models.CharField(max_length=500)),
                ('sequence', models.TextField()),
                ('structure', models.TextField()),
                ('folding_free_energy', models.FloatField()),
                ('cai', models.FloatField()),
            ],
            options={
                'verbose_name': 'lineardesign_taskresult',
                'verbose_name_plural': 'lineardesign_taskresult',
                'db_table': 'lineardesign_taskresult',
            },
        ),
    ]
