# Generated by Django 4.2.1 on 2023-06-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phage', '0009_rename_group_phage_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_trna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trna_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trnatype', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('permutation', models.TextField(blank=True, null=True)),
                ('seq', models.TextField(blank=True, null=True)),
                ('phage_accid', models.CharField(blank=True, max_length=200, null=True)),
                ('phage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phage.phage')),
            ],
            options={
                'verbose_name': 'phage_trna',
                'verbose_name_plural': 'phage_trna',
                'db_table': 'phage_trna',
            },
        ),
    ]
