# Generated by Django 4.2.1 on 2023-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_trna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage_trna',
            name='end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phage_trna',
            name='start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phage_trna',
            name='strand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
