# Generated by Django 4.2.1 on 2025-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='protein_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField()),
                ('seq_acc', models.CharField()),
                ('overall_gc', models.FloatField(blank=True, null=True)),
                ('codon_usage_efficiency_index', models.FloatField(blank=True, null=True)),
                ('tis', models.FloatField(blank=True, null=True)),
                ('rna_interference', models.IntegerField(blank=True, null=True)),
                ('rna_structure', models.IntegerField(blank=True, null=True)),
                ('ires_number', models.IntegerField(blank=True, null=True)),
                ('degscore', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'protein_score',
                'verbose_name_plural': 'protein_score',
                'db_table': 'protein_score',
            },
        ),
    ]
