# Generated by Django 4.2.23 on 2025-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transcripthub_assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(blank=True, max_length=200, null=True)),
                ('record', models.CharField(blank=True, max_length=200, null=True)),
                ('seqname', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('feature', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=5, null=True)),
                ('frame', models.CharField(blank=True, max_length=5, null=True)),
                ('attribute', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'transcripthub_assembly',
                'verbose_name_plural': 'transcripthub_assembly',
                'db_table': 'transcripthub_assembly',
            },
        ),
    ]
