# Generated by Django 4.2.23 on 2025-09-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcripthub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genome_seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqname', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'genome_seq',
                'verbose_name_plural': 'genome_seq',
                'db_table': 'genome_seq',
            },
        ),
        migrations.CreateModel(
            name='transcripthub_annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(blank=True, max_length=200, null=True)),
                ('record', models.CharField(blank=True, max_length=200, null=True)),
                ('seqname', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('feature', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=5, null=True)),
                ('frame', models.CharField(blank=True, max_length=5, null=True)),
                ('attribute', models.TextField(blank=True, null=True)),
                ('genome_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts', to='transcripthub.genome_seq')),
            ],
            options={
                'verbose_name': 'transcripthub_annotation',
                'verbose_name_plural': 'transcripthub_annotation',
                'db_table': 'transcripthub_annotation',
            },
        ),
    ]
