# Generated by Django 4.2.1 on 2024-10-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tantigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agacc', models.CharField(blank=True, max_length=20, null=True)),
                ('antigen_name', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('synonym', models.TextField(blank=True, null=True)),
                ('uniprot_id', models.CharField(blank=True, max_length=20, null=True)),
                ('href1', models.TextField(blank=True, max_length=200, null=True)),
                ('ncbi_gene_id', models.CharField(blank=True, max_length=20, null=True)),
                ('href2', models.TextField(blank=True, max_length=200, null=True)),
                ('gene_card_id', models.CharField(blank=True, max_length=20, null=True)),
                ('href3', models.TextField(blank=True, max_length=200, null=True)),
                ('rna_or_protein_expression_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('href4', models.TextField(blank=True, max_length=200, null=True)),
                ('antigen_sequence', models.TextField(blank=True, null=True)),
                ('seq_5', models.TextField(blank=True, null=True)),
                ('cds', models.TextField(blank=True, null=True)),
                ('seq_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tantigen',
                'verbose_name_plural': 'tantigen',
                'db_table': 'tantigen',
            },
        ),
    ]
