# Generated by Django 4.2.1 on 2025-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gtrnadb_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomeid', models.CharField(max_length=200)),
                ('gtrnadb_id', models.CharField(max_length=200)),
                ('trna_scan_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trna_scan_id_code', models.CharField(blank=True, max_length=200, null=True)),
                ('chr', models.CharField(blank=True, max_length=200, null=True)),
                ('start', models.CharField(blank=True, max_length=100, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('strand', models.CharField(blank=True, max_length=100, null=True)),
                ('isotype', models.CharField(blank=True, max_length=200, null=True)),
                ('anticodon', models.CharField(blank=True, max_length=200, null=True)),
                ('intron_count', models.IntegerField(blank=True, null=True)),
                ('mismatches', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('pseudogene', models.IntegerField(blank=True, null=True)),
                ('ids', models.CharField(max_length=300)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('len_mature', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'gtrnadb_data',
                'verbose_name_plural': 'gtrnadb_data',
                'db_table': 'gtrnadb_data',
            },
        ),
        migrations.CreateModel(
            name='gtrnadb_genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('genome', models.CharField(max_length=300)),
                ('genomeid', models.CharField(max_length=200)),
                ('gtrnadb_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('genbank_common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'gtrnadb_genome',
                'verbose_name_plural': 'gtrnadb_genome',
                'db_table': 'gtrnadb_genome',
            },
        ),
    ]
