# Generated by Django 4.2.1 on 2024-10-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='three_utr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ensembl_gene_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ensembl_transcript_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('start_position', models.IntegerField(blank=True, null=True)),
                ('end_position', models.IntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=100, null=True)),
                ('aliases', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'three_utr',
                'verbose_name_plural': 'three_utr',
                'db_table': 'three_utr',
            },
        ),
    ]
