# Generated by Django 4.2.1 on 2024-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tantigen_rna_seq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agacc', models.TextField(blank=True, null=True)),
                ('antigen_name', models.CharField(blank=True, max_length=20, null=True)),
                ('seq_5', models.TextField(blank=True, null=True)),
                ('cds', models.TextField(blank=True, null=True)),
                ('seq_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tantigen_rna_seq',
                'verbose_name_plural': 'tantigen_rna_seq',
                'db_table': 'tantigen_rna_seq',
            },
        ),
    ]
