# Generated by Django 4.1.2 on 2023-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phage_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Acession_ID', models.CharField(blank=True, max_length=30, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('gc_content', models.CharField(blank=True, max_length=50, null=True)),
                ('Phage_sequence_file_path', models.CharField(blank=True, max_length=50, null=True)),
                ('host_id', models.IntegerField(blank=True, null=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('Data_Sets_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'phages',
                'verbose_name_plural': 'phages',
                'db_table': 'phages',
            },
        ),
    ]
