# Generated by Django 4.2.1 on 2023-05-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_datasets_sets'),
        ('phage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phage',
            name='Data_Sets_id',
        ),
        migrations.RemoveField(
            model_name='phage',
            name='Phage_sequence_file_path',
        ),
        migrations.RemoveField(
            model_name='phage',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='phage',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='phage',
            name='phage_name',
        ),
        migrations.AddField(
            model_name='phage',
            name='Data_Sets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='datasets.datasets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phage',
            name='host',
            field=models.CharField(blank=True, null=True),
        ),
    ]
