# Generated by Django 4.2.1 on 2023-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0002_remove_phage_data_sets_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phage',
            name='Acession_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
