# Generated by Django 4.2.1 on 2023-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0005_alter_phage_acession_id_alter_phage_gc_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='completeness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='taxonomy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
