# Generated by Django 4.2.1 on 2023-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0006_phage_completeness_phage_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
