# Generated by Django 4.2.1 on 2023-05-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0007_phage_cluster_phage_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phage',
            old_name='cluster',
            new_name='subcluster',
        ),
    ]
