# Generated by Django 4.2.1 on 2023-05-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0008_rename_cluster_phage_subcluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phage',
            old_name='group',
            new_name='cluster',
        ),
    ]
