# Generated by Django 4.2.1 on 2023-06-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0009_rename_group_phage_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
