# Generated by Django 4.2.1 on 2023-08-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0012_alter_phage_display_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phage',
            name='display_id',
        ),
    ]
