# Generated by Django 4.2.1 on 2023-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0014_phage_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
    ]
