# Generated by Django 4.2.1 on 2023-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage', '0015_phage_is_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='is_redundant',
            field=models.BooleanField(default=False),
        ),
    ]
