# Generated by Django 4.1.2 on 2023-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phage_hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('host_ref', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'phage_hosts',
                'verbose_name_plural': 'phage_hosts',
                'db_table': 'phage_hosts',
            },
        ),
    ]
