# Generated by Django 4.2.1 on 2023-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_hosts', '0002_remove_phage_hosts_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phage_hosts',
            old_name='name',
            new_name='host',
        ),
        migrations.AddField(
            model_name='phage_hosts',
            name='accesion_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage_hosts',
            name='Class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage_hosts',
            name='Family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage_hosts',
            name='Genus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage_hosts',
            name='Order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage_hosts',
            name='Phylum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
