# Generated by Django 4.2.1 on 2023-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_hosts', '0003_rename_name_phage_hosts_host_phage_hosts_accesion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage_hosts',
            name='Species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
