# Generated by Django 4.2.1 on 2023-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_hosts', '0004_phage_hosts_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='phage_hostnode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'phage_hostnode',
                'verbose_name_plural': 'phage_hostnode',
                'db_table': 'phage_hostnode',
            },
        ),
    ]
