# Generated by Django 4.2.1 on 2023-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phage_hosts', '0005_phage_hostnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage_hostnode',
            name='phagecount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phage_hostnode',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
