# Generated by Django 4.2.1 on 2025-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.IntegerField()),
                ('gene_id_str', models.CharField(blank=True, max_length=200, null=True)),
                ('transcript_id', models.IntegerField()),
                ('transcript_id_str', models.CharField(blank=True, max_length=200, null=True)),
                ('sample_id', models.IntegerField()),
                ('sample_id_str', models.CharField(blank=True, max_length=200, null=True)),
                ('cov', models.FloatField(null=True)),
                ('fpkm', models.FloatField(null=True)),
                ('tpm', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'expression_record',
                'verbose_name_plural': 'expression_record',
                'db_table': 'expression_record',
            },
        ),
        migrations.AddConstraint(
            model_name='expressionrecord',
            constraint=models.UniqueConstraint(fields=('sample_id', 'transcript_id'), name='unique_sample_transcript'),
        ),
    ]
